# Generated by Django 5.2.17 on 2026-08-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, help_text='Unique barcode provided to the customer', max_length=64, unique=True)),
                ('vehicle_number', models.CharField(max_length=64)),
                ('customer_name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('service_done_date', models.DateField()),
                ('warranty_expiry_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Warranty',
                'verbose_name_plural': 'Vehicle Warranties',
                'ordering': ['-service_done_date', '-created_at'],
            },
        ),
    ]
