# Generated by Django 5.2.17 on 2026-08-29 08:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclewarranty',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='vehiclewarranty',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='vehiclewarranty',
            name='warranty_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehiclewarranty',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
